### PR TITLE
Added Arduino tutorials under C/C++ topic in README.md (Issue #94)

### PR DESCRIPTION
**Pull request by lucastosetto**
## Description

New topic named "Arduino" was added in C/C++ section of the README.md file with links to Arduino official website tutorials. The tutorials were chosen and organized in a logical sequence in order to provide the opportunity for begginers to have a general contact with the application and from there build more skills.

## Motivation and Context

Fix Issue #94 .

## How Has This Been Tested?

All the procedures was tested during my trajectory as and Arduino programmer in an Arduino Nano board, a protoboard, a PC running Windows 10 and the Arduino IDE.

## Types of changes

- [ ] Content Update (change which fixes an issue or updates an already existing submission)
- [x] New Article (change which adds functionality)
- [ ] Documentation change

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have made checks to ensure URLs and other resources are valid

### CODE REVIEW

**Comment by enkeyz** [comment]
Arduino should be a subcategory.

**Review by its0x08 — APPROVED** [review]

**Comment by enkeyz** [comment]
@its0x08 your approve also a mistake here, Arduino should be a subcategory: take a look at this example: https://github.com/practical-tutorials/project-based-learning/blob/0d3b4e535ccb1be6d3e637eac5e694d67fb8f60c/README.md?plain=1#L131

**Comment by its0x08** [comment]
@enkeyz probably you are right..

**Comment by enkeyz** [comment]
Also, these tutorials are from the offical Arduino website. Closing.

**Pull request closed without merging**
